In [ ]:
import pandas as pd
df = pd.read_csv("vendas.csv")
df.head()

,data,produto,categoria,quantidade,preco_unitario,vendedor,regiao
0,2024-01-03,Notebook Dell,Eletrônicos,2,3500.0,Ana Lima,Sul
1,2024-01-05,Mouse Logitech,Eletrônicos,5,150.0,Carlos Souza,Sudeste
2,2024-01-07,Cadeira Gamer,Móveis,1,1200.0,Ana Lima,Sul
3,2024-01-10,Monitor LG,Eletrônicos,3,900.0,Fernanda Costa,Nordeste
4,2024-01-12,Teclado Mecânico,Eletrônicos,4,350.0,Carlos Souza,Sudeste

In [ ]:
import pandas as pd
df = pd.read_csv("vendas.csv")
df.head()

df.shape
# (300, 8) → linhas, colunas
df.describe()
# resumo estatístico automático

       quantidade  preco_unitario
count   30.000000       30.000000
mean     3.566667     1066.333333
std      2.176415     1150.347724
min      1.000000      150.000000
25%      2.000000      350.000000
50%      3.000000      625.000000
75%      4.750000     1125.000000
max     10.000000     3500.000000

In [ ]:
import pandas as pd
df = pd.read_csv("vendas.csv")
df.head()

df.shape
# (300, 8) → linhas, colunas
df.describe()
# resumo estatístico automático

df[df["vendedor"] == "Ana Lima"]
df[df["preco_unitario"] > 1000]

,data,produto,categoria,quantidade,preco_unitario,vendedor,regiao
0,2024-01-03,Notebook Dell,Eletrônicos,2,3500.0,Ana Lima,Sul
2,2024-01-07,Cadeira Gamer,Móveis,1,1200.0,Ana Lima,Sul
6,2024-01-18,Notebook Dell,Eletrônicos,1,3500.0,Fernanda Costa,Nordeste
10,2024-02-01,Notebook Dell,Eletrônicos,3,3500.0,Ana Lima,Sul
11,2024-02-03,Cadeira Gamer,Móveis,2,1200.0,Fernanda Costa,Nordeste
19,2024-02-22,Notebook Dell,Eletrônicos,2,3500.0,Carlos Souza,Sudeste
21,2024-03-03,Cadeira Gamer,Móveis,3,1200.0,Ana Lima,Sul
24,2024-03-10,Notebook Dell,Eletrônicos,1,3500.0,Fernanda Costa,Nordeste

In [ ]:
import pandas as pd
df = pd.read_csv("vendas.csv")
df.head()

df.shape
# (300, 8) → linhas, colunas
df.describe()
# resumo estatístico automático

df[df["vendedor"] == "Ana Lima"]
df[df["preco_unitario"] > 1000]

df["total"] = (
 df["quantidade"] *
 df["preco_unitario"]
)
df["total"].sum()

np.float64(77870.0)

In [ ]:
import pandas as pd
df = pd.read_csv("vendas.csv")
df.head()

df.shape
# (300, 8) → linhas, colunas
df.describe()
# resumo estatístico automático

df[df["vendedor"] == "Ana Lima"]
df[df["preco_unitario"] > 1000]

df["total"] = (
 df["quantidade"] *
 df["preco_unitario"]
)
df["total"].sum()

df.groupby("vendedor")["total"].sum().sort_values(ascending=False)

vendedor
Ana Lima          33060.0
Carlos Souza      18600.0
Fernanda Costa    18550.0
João Mendes        7660.0
Name: total, dtype: float64